#!/bin/sh
# requires sqlite3 (3.8.8.2)
cd "$(dirname "$0")"

echo 'Generate SQL queries for CSV files to import'
echo '-- list of CSV files to import generated by import.sh' > import_csv.sql
for file in ../step1/*.csv
do
  table="$(basename "$file" .csv)"
  echo ".import $file $table"
done >> import_csv.sql

echo 'Import CSV files into a new sqlite database'
sqlite3 < import.sql

echo 'Collect all files from data/ folders into a single data/ directory'
rm -rf data
mkdir data
cp ../../sources/*/*/data/* data/
