#!/bin/sh
# requires sqlite3 (3.8.8.2)
cd "$(dirname "$0")"

echo '-- list of CSV files to import generated by import.sh' > import_csv.sql
for file in ../step1/*.csv
do
  table="$(basename "$file" .csv)"
  echo ".import $file $table"
done >> import_csv.sql

sqlite3 < import.sql
