#!/bin/sh
# requires sqlite3 (3.8.8.2)
# requires csvcut, from csvkit (0.9.0)
# requires csvformat, from csvkit (0.9.0)
# requires erd

cd "$(dirname "$0")"

echo 'List tables'
sqlite3 < list_tables.sql

cat << EOF > list_table_fields.sql
-- queries to export the fields of each table, generated by document.sh
.read ../step5/database.sql
.headers on
.nullvalue NULL
.mode csv
EOF

csvcut -c2 database_tables.csv |
tail -n +2 | # skip header
while read tableName
do
  echo ".once table_info_$tableName.csv"
  echo "pragma table_info($tableName);"
done >> list_table_fields.sql

echo 'Delete previous lists of fields'
rm -f table_info_*.csv

echo 'List fields of each database table'
sqlite3 < list_table_fields.sql

echo 'Combine table fields in a single file,'
echo 'adding type and name of table for disambiguation.'

tableHeader=''
while IFS="$IFS" read tableRecord
do
  if test -z "$tableHeader"
  then
    tableHeader="$tableRecord"
  else
    tableName="$(echo "$tableRecord" | csvcut -c2)"
    fieldsHeader=''

    while IFS='' read fieldsRecord
    do
      if test -z "$fieldsHeader"
      then
        fieldsHeader="$fieldsRecord"
        if test -z "$combinedHeader"
        then
          combinedHeader="$tableHeader,$fieldsHeader"
          echo "$combinedHeader"
        fi
      else
        echo "$tableRecord,$fieldsRecord"
      fi
    done < "table_info_$tableName.csv"
  fi
done < database_tables.csv > database_table_fields.csv

# TODO: convert to erd format

# TODO: combine with extra information (references) and styles for display

# TODO: convert from erd format to PNG


